[build]
  # No build command needed for static site
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Configure function settings
  node_bundler = "esbuild"
  
[functions."generate-video"]
  # Maximum timeout for Netlify functions (26 seconds)
  # Video generation takes time, this is the max allowed
  timeout = 26

[functions."generate-video-webhook"]
  # Webhook function needs maximum timeout to wait for Blackbox API
  timeout = 26

[functions."start-video"]
  # Quick function, just creates job and triggers webhook
  timeout = 10

[functions."check-video-status"]
  # Quick function, just checks job status
  timeout = 10
